# Generated by Django 5.2.3 on 2025-07-10 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=10)),
                ('price', models.FloatField()),
                ('stoack', models.IntegerField()),
                ('category', models.CharField(max_length=15)),
            ],
        ),
    ]
