# Generated by Django 5.2.3 on 2025-07-10 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinfo',
            old_name='stoack',
            new_name='stock',
        ),
    ]
