# Generated by Django 5.2.3 on 2025-06-30 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studName', models.TextField(max_length=10)),
                ('age', models.IntegerField(max_length=2)),
                ('stream', models.TextField(max_length=10)),
                ('marks', models.IntegerField(max_length=3)),
                ('city', models.TextField(max_length=15)),
            ],
        ),
    ]
