# Generated by Django 5.2.3 on 2025-07-01 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.TextField(max_length=30)),
                ('price', models.IntegerField()),
                ('description', models.TextField(max_length=50)),
                ('offer', models.TextField(max_length=5)),
                ('productimages', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('category', models.TextField(max_length=20)),
            ],
        ),
    ]
