# Generated by Django 5.2.3 on 2025-06-27 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.IntegerField(max_length=2)),
                ('studname', models.TextField(max_length=8)),
                ('studage', models.FloatField()),
                ('stream', models.TextField(max_length=10)),
                ('marks', models.IntegerField()),
            ],
        ),
    ]
